library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("route/", include("route.urls", namespace="routr")),
    path("polls/", include("polls.urls", namespace="polls")),
    path("movie/", include("moviefacts.urls", namespace="moviefacts")),
    path("polls/generic/", include("polls.urls_gen", namespace="polls_gen")),
    path("users/", include("user.urls", namespace="user")),
    path("__debug__/", include("debug_toolbar.urls")),
]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("customer/", views.CustomerCreateView.as_view(), name="customer"),
]

app_name = "polls"

user/urls.py
from django.urls import path, include
from user.views import dashboard, MyPasswordChangeView, MyPasswordChangeDoneView, MyLoginView, MyPasswordResetView, \
    MyPasswordResetDoneView, MyPasswordResetConfirmView, MyPasswordResetCompleteView, register

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "accounts/password_change/", MyPasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "accounts/password_change/done/",
        MyPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("accounts/login/", MyLoginView.as_view(), name="login"),
    path("accounts/password_reset/", MyPasswordResetView.as_view(), name="password_reset"),
    path(
        "accounts/password_reset/done/",
        MyPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),

    path(
        "accounts/reset/<uidb64>/<token>/",
        MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        MyPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/register', register, name='register'),
]

app_name = "user"

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"question: {self.question_text}, published: {self.pub_date}"


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"choice for question {self.question}, text: {self.choice_text}"


class Customer(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    hobby = models.CharField("my hobby", max_length=64, null=True, blank=True)

polls/views.py
from django.http import HttpRequest, HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from polls.models import Choice, Customer, Question


class CustomerCreateView(generic.CreateView):
    model = Customer
    success_url = reverse_lazy("polls:index", args=())
    template_name = "polls/customer.html"
    fields = "__all__"


def index(request: HttpRequest) -> HttpResponse:
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "polls/index.html", context)


def detail(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {"question": question,"error_message": "You didn't select a choice."}
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(DetailView):
    template_name = "polls/results.html"



polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Polls
        {% endblock title %}
    </title>
</head>
<body>
        {% block head %}
            <a href="{% url 'polls:index' %}">Main page</a>
            <a href="{% url 'polls:customer' %}">Input name</a>
        {% endblock head %}

        {% block content %}
        {% endblock content %}

</body>
</html>

polls/templates/polls/customer.html
{% extends 'polls/base.html' %}

{% block content %}
    <br>
<form action="" method="post" novalidate>
{% csrf_token %}
    {{ form.as_p }}
    <br>
<input type="submit" value="Submit">
</form>
{% endblock content %}

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}



<form action="{% url 'polls_gen:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h2>{{ question.question_text }}</h2></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <label>
             <input type="radio" name="choice" value="{{ choice.id }}">
            {{ choice.choice_text }}
        </label>
       <br>
    {% endfor %}
</fieldset>
<br>
<input type="submit" value="Vote">
</form>

{% endblock content %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls_gen:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock content %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}
    <h2>{{ question.question_text }}</h2>
    <hr>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

{% endblock content %}